//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvlocal_gui.LAB.SETTINGS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class CompilerOptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static CompilerOptions defaultInstance = ((CompilerOptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CompilerOptions())));
        
        public static CompilerOptions Default {
            get {
                return defaultInstance;
            }
        }
    }
}
